#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
        /usr/sbin/service solr stop 2> /dev/null > /dev/null || true
    ;;
    failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
